In [1]:
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

Unlike the graph mode, where we need to construct a graph
 every time to perform any operations, eager execution follows the imperative
 programming paradigm, where any operations can be performed
 immediately, without having to create a graph, just like we do in Python.

In [2]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y
print(z)

tf.Tensor(121, shape=(), dtype=int32)


In [3]:
z.numpy()

np.int32(121)

In [4]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

In [5]:
sum = tf.add(x,y)
sum.numpy()

array([4., 4., 4.], dtype=float32)

In [6]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

In [7]:
product = tf.multiply(x,y)
product.numpy()

array([3., 4., 3.], dtype=float32)

In [8]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

In [9]:
dot_product = tf.reduce_sum(tf.multiply(x, y))
dot_product.numpy()

np.float32(10.0)

In [10]:
x = tf.constant([10, 0, 13, 9])
print(tf.argmin(x).numpy())
print(tf.argmax(x).numpy())

1
2


In [11]:
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])
tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

In [12]:
print(x.dtype)

<dtype: 'int32'>


In [13]:
x = tf.cast(x, dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


In [14]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

In [15]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

In [16]:
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]], dtype=int32)

In [17]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

In [18]:
tf.reduce_mean(input_tensor=x).numpy()

np.float32(2.75)

Computing the mean across the column; that is, (1.0+5.0)/2.0, (2.0+3.0)/2.0:

In [19]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

In [20]:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()
tf.random.uniform(shape = (3,2), minval=0, maxval=None, dtype=tf.float32,).numpy()

array([[0.28722966, 0.11389112],
       [0.35883605, 0.2814728 ],
       [0.30603957, 0.99148643]], dtype=float32)

In [21]:
x = tf.constant([7., 2., 5.])
tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

In [22]:
def square(x):
    return tf.multiply(x, x)

In [23]:
with tf.GradientTape(persistent=True) as tape:
    print(square(6.).numpy())

36.0
